import { Layout, Text, Page } from "@vercel/examples-ui";
import Head from "next/head";
import { Chat } from "../components/Chat";
import styles from "@/styles/Home.module.css";
function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex w-9/12 flex-col mx-auto items-center justify-center py-2 min-h-screen">
          <Text variant="h2" className="mb-10">
            AI Chat Bot:
          </Text>
          <div className="lg:w-2/3 h-[50vh]">
            <Chat />
          </div>
        </div>
      </main>
    </>
  );
}

Home.Layout = Layout;

export default Home;
