import { Layout, Text, Page } from "@vercel/examples-ui";
import Head from "next/head";
import styles from "@/styles/Transcribe.module.css";
import { ChangeEvent, useEffect, useState } from "react";
import { Toaster, toast } from "react-hot-toast";
import InputForm from "@/components/InputForm";

function Transcribe() {
  const [loading, setLoading] = useState(false);
  const [text, setText] = useState("");
  const [transcripts, setTranscripts] = useState<string[]>([]);
  const [currentTranscript, setCurrentTranscript] = useState("");
  const [transcriptIndex, setTranscriptIndex] = useState(-1);
  const TYPING_RATE = 5;

  const generateTranscription = async (
    e: any,
    url: string,
    file: ReadableStream | undefined,
    acc: string
  ) => {
    e.preventDefault();
    if (!(url || file)) return;

    setText("");
    setTranscripts([]);
    setCurrentTranscript("");
    setTranscriptIndex(-1);
    setLoading(false);

    const response = await fetch("/api/transcribe", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        vidURL: url,
        vidStream: file,
        acc: acc,
      }),
    });

    if (!response.ok) {
      throw new Error(response.statusText);
    }

    // This data is a ReadableStream
    const data = response.body;
    if (!data) {
      return;
    }

    const reader = data.getReader();
    const decoder = new TextDecoder();
    let done = false;

    let firstChunk = true;
    while (!done) {
      const { value, done: doneReading } = await reader.read();
      done = doneReading;
      let chunkValue = decoder.decode(value);
      if (firstChunk) {
        firstChunk = false;
        chunkValue = chunkValue.trimStart();
      }
      console.log("setting transcripts", transcripts.length);
      setTranscripts([...transcripts, chunkValue]);
    }
    // setLoading(false);
  };

  const updateTranscriptSmooth = () => {
    console.log("t", transcripts.length);
    if (transcripts.length) {
      setLoading(true);
      setCurrentTranscript(transcripts[0] as string);
      setTranscripts(transcripts.slice(1));
      // setTranscripts(transcripts);
      setTranscriptIndex(0);
    }
  };

  useEffect(() => {
    if (!currentTranscript) return;
    setTimeout(function updateTimeout() {
      if (transcriptIndex >= currentTranscript.length) {
        setLoading(false);
        return;
      }
      setText(
        (prev) =>
          prev +
          currentTranscript.substring(
            transcriptIndex,
            Math.min(
              transcriptIndex + TYPING_RATE + 1,
              currentTranscript.length
            )
          )
      );
      setTranscriptIndex(transcriptIndex + TYPING_RATE + 1);
    }, 20);
  }, [transcriptIndex]);

  useEffect(() => {
    if (loading == false) {
      updateTranscriptSmooth();
    }
  }, [loading]);

  useEffect(() => {
    console.log(loading, transcripts.length);
    if (loading == false && transcripts.length) updateTranscriptSmooth();
  }, [transcripts]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex w-9/12 flex-col mx-auto py-2 min-h-screen">
          <InputForm onSubmit={generateTranscription} submitText="Transcribe" />
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{ duration: 2000 }}
          />
          <div className="space-y-10 my-10">
            {text && (
              <>
                <div>
                  <h1 className="flex justify-center mt-32 w-full mb-2 text-5xl mx-auto font-medium leading-tight text-primary">
                    Transcript
                  </h1>
                </div>
                <div className="space-y-8 flex flex-col items-center justify-center mx-auto max-w-full whitespace-pre">
                  <div
                    className="bg-white rounded-xl shadow-md p-4 hover:bg-gray-100 transition cursor-copy border"
                    onClick={() => {
                      navigator.clipboard.writeText(text.toString());
                      toast("Transcript copied to clipboard", {
                        icon: "✂️",
                      });
                    }}
                  >
                    <p className={styles.transcription}>{text}</p>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      </main>
    </>
  );
}

Transcribe.Layout = Layout;

export default Transcribe;
