import { Layout, Text, Page } from "@vercel/examples-ui";
import Head from "next/head";
import styles from "@/styles/Transcribe.module.css";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Toaster, toast } from "react-hot-toast";
import InputForm from "@/components/InputForm";
import ProgressBar from "@/components/ProgressBar";

function Transcribe() {
  const [loading, setLoading] = useState(false);
  const [text, setText] = useState("");
  const [currentTranscript, setCurrentTranscript] = useState("");
  const [transcriptIndex, setTranscriptIndex] = useState(-1);

  const [progVisible, setProgVisible] = useState(false);
  const [progress, setProgress] = useState(0);
  const [status, setStatus] = useState("");

  const TYPING_RATE = 5;

  const bioRef = useRef<null | HTMLDivElement>(null);

  const scrollToBios = () => {
    if (bioRef.current !== null) {
      bioRef.current.scrollIntoView({ behavior: "smooth" });
    }
  };

  const generateTranscription = async (
    e: any,
    url: string,
    file: File | undefined,
    acc: string
  ) => {
    e.preventDefault();
    if (!(url || file)) return;

    setText("");
    setCurrentTranscript("");
    setTranscriptIndex(-1);
    setLoading(false);

    setProgress(0);
    setProgVisible(true);
    setStatus("Downloading video");

    let response;
    if (file) {
      const body = new FormData();
      body.append("file", file);
      response = await fetch("/api/transcribe", {
        method: "POST",
        headers: {
          "x-accuracy": acc,
        },
        body,
      });
    } else {
      response = await fetch("/api/transcribe", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-accuracy": acc,
        },
        body: JSON.stringify({
          vidURL: url,
        }),
      });
    }

    if (!response.ok) {
      throw new Error(response.statusText);
    }

    // This data is a ReadableStream
    const data = response.body;
    if (!data) {
      return;
    }

    const reader = data.getReader();
    const decoder = new TextDecoder();
    let done = false;

    let firstChunk = true;

    let audioDuration = 0;
    let messageLength = 0;
    let audioDownload = 0;

    let audio_download_start = url ? 10 : undefined;
    let transcript_start = audio_download_start ? 30 : 10;
    let transcript_end = 100;

    setProgress(audio_download_start || transcript_start);
    setLoading(true);
    while (!done) {
      const { value, done: doneReading } = await reader.read();
      done = doneReading;
      let chunkValue = decoder.decode(value);
      if (/^info: /g.test(chunkValue)) {
        setStatus(chunkValue.replace(/^info: /g, ""));
        continue;
      }
      if (/\|\|backend: (.*?)\|\|/g.test(chunkValue)) {
        let params = new URLSearchParams(
          chunkValue.match(/\|\|backend: (.*?)\|\|/)![1]
        );
        if (chunkValue.includes("message")) console.log(chunkValue);
        if (params.get("audio_duration"))
          audioDuration = parseFloat(params.get("audio_duration")!);
        if (params.get("message_length"))
          messageLength = parseInt(params.get("message_length")!);
        if (params.get("audio_download")) {
          audioDownload = parseFloat(params.get("audio_download")!);
          setProgress((prev) =>
            Math.min(
              parseFloat(
                (
                  prev +
                  audioDownload * (transcript_start - audio_download_start!)
                ).toFixed(2)
              ),
              transcript_start
            )
          );
        }
        chunkValue = chunkValue.replace(/\|\|backend: (.*?)\|\|/g, "");
      }

      if (!chunkValue) continue;

      if (audioDuration && messageLength)
        setProgress((prev) =>
          Math.min(
            parseFloat(
              (
                prev +
                (chunkValue.length / messageLength) *
                  (30 / audioDuration) *
                  (transcript_end - transcript_start)
              ).toFixed(2)
            ),
            transcript_end
          )
        );
      if (firstChunk) {
        firstChunk = false;
        chunkValue = chunkValue.trimStart();
      }

      scrollToBios();
      setText((prev) => prev + chunkValue);
    }

    setProgress(100);
    setStatus("Finished");
    // setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex w-9/12 flex-col mx-auto py-2 min-h-screen">
          <InputForm onSubmit={generateTranscription} submitText="Transcribe" />
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{ duration: 2000 }}
          />
          {progVisible ? (
            <ProgressBar progress={progress} status={status} />
          ) : null}
          <div className="space-y-10 my-10">
            {text && (
              <>
                <div>
                  <h1 className="flex justify-center mt-32 w-full mb-2 text-5xl mx-auto font-medium leading-tight text-primary">
                    Transcript
                  </h1>
                </div>
                <div
                  className="bg-white rounded-xl shadow-md p-4 hover:bg-gray-100 transition cursor-copy border"
                  onClick={() => {
                    navigator.clipboard.writeText(text.toString());
                    toast("Transcript copied to clipboard", {
                      icon: "✂️",
                    });
                  }}
                >
                  <p className={styles.transcription}>{text}</p>
                </div>
                <div ref={bioRef} />
              </>
            )}
          </div>
        </div>
      </main>
    </>
  );
}

Transcribe.Layout = Layout;

export default Transcribe;
